timestamp,activo,action,method,success,info
2025-10-03 12:13:13,EURUSD,initial_test,buy_digital_spot,False,timeout after 7s
2025-10-03 12:13:14,EURUSD,initial_test,buy,True,"(False, 'Cannot purchase an option (active is suspended)')"
2025-10-03 12:13:14,EURUSD,initial_test,buy_digital,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_digital() takes 3 positional arguments but 5 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_digital() takes 3 positional arguments but 5 were given
"
2025-10-03 12:13:14,EURUSD,initial_test,buy_by_raw_expirations,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_by_raw_expirations() missing 1 required positional argument: 'expired'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_by_raw_expirations() missing 1 required positional argument: 'expired'
"
2025-10-03 12:13:14,EURUSD,initial_test,buy_multi,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
  File ""C:\Users\alejandro fornerino\AppData\Local\Programs\Python\Python313\Lib\site-packages\iqoptionapi\stable_api.py"", line 751, in buy_multi
    if len(price) == len(ACTIVES) == len(ACTION) == len(expirations):
       ~~~^^^^^^^
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
  File ""C:\Users\alejandro fornerino\AppData\Local\Programs\Python\Python313\Lib\site-packages\iqoptionapi\stable_api.py"", line 751, in buy_multi
    if len(price) == len(ACTIVES) == len(ACTION) == len(expirations):
                     ~~~^^^^^^^^^
TypeError: object of type 'int' has no len()
"
2025-10-03 12:13:15,EURUSD,initial_test,buy_order,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_order() missing 2 required positional arguments: 'leverage' and 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_order() missing 2 required positional arguments: 'leverage' and 'type'
"
2025-10-03 12:13:15,EURUSD,initial_sequence,all_failed,False,None
2025-10-03 12:13:23,GBPUSD,initial_test,buy_digital_spot,False,timeout after 7s
2025-10-03 12:13:23,GBPUSD,initial_test,buy,True,"(False, 'Cannot purchase an option (active is suspended)')"
2025-10-03 12:13:24,GBPUSD,initial_test,buy_digital,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_digital() takes 3 positional arguments but 5 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_digital() takes 3 positional arguments but 5 were given
"
2025-10-03 12:13:24,GBPUSD,initial_test,buy_by_raw_expirations,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_by_raw_expirations() missing 1 required positional argument: 'expired'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_by_raw_expirations() missing 1 required positional argument: 'expired'
"
2025-10-03 12:13:24,GBPUSD,initial_test,buy_multi,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
  File ""C:\Users\alejandro fornerino\AppData\Local\Programs\Python\Python313\Lib\site-packages\iqoptionapi\stable_api.py"", line 751, in buy_multi
    if len(price) == len(ACTIVES) == len(ACTION) == len(expirations):
       ~~~^^^^^^^
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
  File ""C:\Users\alejandro fornerino\AppData\Local\Programs\Python\Python313\Lib\site-packages\iqoptionapi\stable_api.py"", line 751, in buy_multi
    if len(price) == len(ACTIVES) == len(ACTION) == len(expirations):
                     ~~~^^^^^^^^^
TypeError: object of type 'int' has no len()
"
2025-10-03 12:13:25,GBPUSD,initial_test,buy_order,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_order() missing 2 required positional arguments: 'leverage' and 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_order() missing 2 required positional arguments: 'leverage' and 'type'
"
2025-10-03 12:13:25,GBPUSD,initial_sequence,all_failed,False,None
2025-10-03 12:13:33,USDJPY,initial_test,buy_digital_spot,False,timeout after 7s
2025-10-03 12:13:34,USDJPY,initial_test,buy,True,"(False, 'Cannot purchase an option (active is suspended)')"
2025-10-03 12:13:34,USDJPY,initial_test,buy_digital,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_digital() takes 3 positional arguments but 5 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_digital() takes 3 positional arguments but 5 were given
"
2025-10-03 12:13:35,USDJPY,initial_test,buy_by_raw_expirations,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_by_raw_expirations() missing 1 required positional argument: 'expired'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_by_raw_expirations() missing 1 required positional argument: 'expired'
"
2025-10-03 12:13:36,USDJPY,initial_test,buy_multi,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
  File ""C:\Users\alejandro fornerino\AppData\Local\Programs\Python\Python313\Lib\site-packages\iqoptionapi\stable_api.py"", line 751, in buy_multi
    if len(price) == len(ACTIVES) == len(ACTION) == len(expirations):
       ~~~^^^^^^^
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
  File ""C:\Users\alejandro fornerino\AppData\Local\Programs\Python\Python313\Lib\site-packages\iqoptionapi\stable_api.py"", line 751, in buy_multi
    if len(price) == len(ACTIVES) == len(ACTION) == len(expirations):
                     ~~~^^^^^^^^^
TypeError: object of type 'int' has no len()
"
2025-10-03 12:13:36,USDJPY,initial_test,buy_order,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_order() missing 2 required positional arguments: 'leverage' and 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_order() missing 2 required positional arguments: 'leverage' and 'type'
"
2025-10-03 12:13:37,USDJPY,initial_sequence,all_failed,False,None
2025-10-03 12:13:45,AUDUSD,initial_test,buy_digital_spot,False,timeout after 7s
2025-10-03 12:13:47,AUDUSD,initial_test,buy,True,"(False, 'Cannot purchase an option (active is suspended)')"
2025-10-03 12:13:47,AUDUSD,initial_test,buy_digital,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_digital() takes 3 positional arguments but 5 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_digital() takes 3 positional arguments but 5 were given
"
2025-10-03 12:13:48,AUDUSD,initial_test,buy_by_raw_expirations,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_by_raw_expirations() missing 1 required positional argument: 'expired'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_by_raw_expirations() missing 1 required positional argument: 'expired'
"
2025-10-03 12:13:49,AUDUSD,initial_test,buy_multi,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
  File ""C:\Users\alejandro fornerino\AppData\Local\Programs\Python\Python313\Lib\site-packages\iqoptionapi\stable_api.py"", line 751, in buy_multi
    if len(price) == len(ACTIVES) == len(ACTION) == len(expirations):
       ~~~^^^^^^^
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
  File ""C:\Users\alejandro fornerino\AppData\Local\Programs\Python\Python313\Lib\site-packages\iqoptionapi\stable_api.py"", line 751, in buy_multi
    if len(price) == len(ACTIVES) == len(ACTION) == len(expirations):
                     ~~~^^^^^^^^^
TypeError: object of type 'int' has no len()
"
2025-10-03 12:13:50,AUDUSD,initial_test,buy_order,False,"Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 127, in wrapper
    return func(amount, activo, direction, expiration_min)
TypeError: IQ_Option.buy_order() missing 2 required positional arguments: 'leverage' and 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 69, in target
    result['res'] = func()
                    ~~~~^^
  File ""C:\Users\alejandro fornerino\Desktop\Nueva carpeta (6)\test.py"", line 130, in wrapper
    return func(activo, amount, direction, expiration_min)
TypeError: IQ_Option.buy_order() missing 2 required positional arguments: 'leverage' and 'type'
"
2025-10-03 12:13:50,AUDUSD,initial_sequence,all_failed,False,None
